// Original mechanical summaries for the currently modeled Artificer,
// Battle Smith, and Warforged catalogs. They avoid reproduced source prose.
export const FEATURE_RULES_2014 = {
  "artificer-magical-tinkering": [
    "Use thieves' tools or artisan's tools to touch a Tiny nonmagical object and give it one minor magical property.",
    "Choose 5-foot bright light plus 5-foot dim light; a 6-second recorded message audible at 10 feet; a continuous odor or nonverbal sound perceptible at 10 feet; or a static visual/message on one surface.",
    "The property lasts indefinitely. End one as an action, and maintain no more than your Intelligence modifier at once (minimum one).",
  ],
  "artificer-spellcasting": [
    "Intelligence is your artificer spellcasting ability; artificer tools can serve as the spellcasting focus.",
    "Prepare a number of artificer spells equal to your Intelligence modifier + half your artificer level, rounded down (minimum one).",
    "Prepared artificer spells with the ritual tag may be cast as rituals. Cantrips and spell slots follow the artificer progression.",
  ],
  "artificer-infuse-item": [
    "Learn artificer infusions according to the class table and apply them to nonmagical objects at the end of a long rest.",
    "Each infusion can normally be active in only one object, and an object can carry only one infusion.",
    "Exceeding your maximum active infusions ends the oldest; an infusion also expires after your death according to the feature's delayed expiry.",
  ],
  "artificer-specialist": ["Choose an artificer specialist. It grants specialist spells and features at the levels shown by that subclass.", "The guided level-up flow records this as a required, persistent subclass choice."],
  "artificer-right-tool": ["With thieves' tools or artisan's tools in hand, spend 1 uninterrupted hour creating one set of artisan's tools in an unoccupied space within 5 feet.", "The created tools are nonmagical and disappear when you use this feature again."],
  "artificer-tool-expertise": ["Double your proficiency bonus on ability checks that use a tool with which you are proficient."],
  "artificer-flash-of-genius": ["When you or a creature you can see within 30 feet makes an ability check or saving throw, use your reaction to add your Intelligence modifier to the roll.", "Use this after seeing the roll but before its outcome. Uses equal your Intelligence modifier (minimum one), restored on a long rest."],
  "artificer-magic-item-adept": ["Attune to as many as four magic items at once.", "Crafting common or uncommon magic items takes one quarter of the normal time and half the normal gold cost."],
  "artificer-spell-storing-item": ["At the end of a long rest, store one 1st- or 2nd-level artificer spell with a 1-action casting time in a simple/martial weapon or artificer focus you touch.", "A creature holding the object uses an action to produce the spell using your spellcasting modifier; that creature maintains concentration when required.", "The object produces the effect twice your Intelligence modifier times (minimum twice), then expires; storing another spell or your next long rest also ends it."],
  "artificer-magic-item-savant": ["Attune to as many as five magic items at once.", "Ignore class, race, spell, and level requirements when attuning to or using a magic item."],
  "artificer-magic-item-master": ["Attune to as many as six magic items at once."],
  "artificer-soul-of-artifice": ["Gain +1 to every saving throw for each magic item you are currently attuned to.", "When reduced to 0 HP but not killed outright, use your reaction to end one artificer infusion and drop to 1 HP instead."],
  "battle-smith-tool-proficiency": ["Gain proficiency with smith's tools. If already proficient, choose another artisan's tool proficiency."],
  "battle-smith-spells": ["Battle Smith specialist spells are always prepared and do not count against the number of artificer spells you prepare."],
  "battle-smith-battle-ready": ["Gain proficiency with martial weapons.", "When attacking with a magic weapon, use Intelligence instead of Strength or Dexterity for attack and damage rolls."],
  "battle-smith-steel-defender": ["At the end of a long rest, create or restore a Steel Defender. Its statistics scale from your Artificer level, proficiency bonus, and Intelligence.", "It acts immediately after your turn. Unless you command another action with your bonus action, it takes Dodge; it can move and use its reaction independently.", "Mending restores HP, and you can revive it shortly after destruction by expending a spell slot. The linked stat block below the Sheet tracks its playable state."],
  "battle-smith-extra-attack": ["Attack twice, rather than once, whenever you take the Attack action on your turn. Extra Attack features do not stack."],
  "battle-smith-arcane-jolt": ["Once per turn after your magic weapon or Steel Defender hits, deal an extra 2d6 force damage or restore 2d6 + Intelligence modifier HP to a creature or object within 30 feet of the target.", "Uses equal your proficiency bonus, restored on a long rest."],
  "battle-smith-improved-defender": ["Your Steel Defender gains +2 AC.", "Arcane Jolt's damage and healing increase from 2d6 to 4d6."],
  "warforged-constructed-resilience": ["Gain advantage on saves against poison and resistance to poison damage.", "You are immune to disease, do not need to eat, drink, or breathe, and do not need sleep; magic cannot put you to sleep."],
  "warforged-sentrys-rest": ["During a long rest, remain motionless and inactive for at least 6 hours while retaining normal awareness and hearing."],
  "warforged-integrated-protection": ["Gain +1 AC.", "Armor must be a type you are proficient with; integrating or removing it takes 1 hour, and integrated armor cannot be removed against your will while you live."],
  "warforged-specialized-design": ["Gain proficiency in one skill and one tool of your choice."],
};
